### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by maxvet** [philnash/send-sms-react-twilio#2]
Hey,
I've followed every step of your tutorial and I'm still getting this error: 

`
Proxy error: Could not proxy request /api/messages from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
`

I've double-checked every step and I've also tried to directly clone your git, but I still get this error. 
Can you help me solve it?

**Comment by philnash** [comment]
How are you starting the application?

**Comment by byronwade** [comment]
Same problem here also. starting the application the same way you say in your README.md doc.

**Comment by philnash** [comment]
This normally means that the server has crashed or can't start for some reason. Can you double check your `.env` file has all the required variables (and thanks for fixing that one variable 😅 already).

**Comment by philnash** [comment]
Hey, are either of you still having this issue?

**Comment by philnash** [comment]
Ok, I'm going to close this for now as I haven't heard back. Please feel free to re-open and share more details if this is still occurring.
