### ISSUE TITLE
Probable typo on Server Side index.js File

### ISSUE THREAD

**Issue by waldothedeveloper** [philnash/send-sms-react-twilio#3]
On the server folder, index.js file, line 21: 

[click here](https://github.com/philnash/send-sms-react-twilio/blame/master/server/index.js#L21)

I think there should be req.header(...) and NOT res.header (for response) right?
Was that a typo?
Or am I totally confused between request and response?

BTW awesome tut! 
I really appreciate putting together this for the community, it really helps!

**Comment by philnash** [comment]
Hey @waldothedeveloper, thanks for asking, I'm always happy to clarify things.

You can call `header` on the request, it's an alias of [`req.get`](https://expressjs.com/en/api.html#req.get) and allows you to retrieve a header sent in via the request. 

However, in this case I am calling `header` on the response, an alias of [`res.set`](https://expressjs.com/en/api.html#res.set) which sets a response header. In this case, I am saying that the response to requests made to `/api/messages` will be of `Content-Type` `application/json`. We then follow this up [by sending JSON responses whether the API request to Twilio succeeds or fails](https://github.com/philnash/send-sms-react-twilio/blob/master/server/index.js#L28-L34).

It occurs to me as I write this that there are two different request and responses in this. This route in the Express application receives an incoming request and sends a JSON response. As part of the execution of the route we also make an API request to Twilio and get the response for that. Calling `res.header('Content-Type', 'application/json')` sets the Express response to be JSON.

Does that make more sense?

**Comment by waldothedeveloper** [comment]
Wow. That was a great explanation. I need to fix my code then LOL. 
I am using your example to build a React front end app that will connect with an AWS API Gateway who’s POST requests will trigger a Lambda function to send SMS using Twilio. But I definitely need to read the express docs to learn what you explained and also the Node JS docs. @philnash thank you I really appreciate taking the time to explain so well.

**Comment by philnash** [comment]
Glad that helped. Let me know if there's anything I can help you with on that Lambda function too (I imagine that might work slightly differently to Express).

**Comment by waldothedeveloper** [comment]
Hey Phil, if you can give me a little help (code review) with that lambda function well I’m super excited!! 
How/Where can I message you to show you more info? 
Thank you again!! 
I’m still learning lots of things and having no mentor is definitely not easy. 
Looking forward to hearing from you man thanks!

**Comment by philnash** [comment]
I'd be happy to take a look. You can get me on email at philnash [at] twilio [dot] com.

**Comment by waldothedeveloper** [comment]
Hi @philnash , I hope this finds you well my friend.
I sent you two emails but I'm not sure if you received them.
I am a little confused about my project and not sure if the sales team could answer my questions...
When you get a chance see if you have received my emails coming from waldothedeveloper [at] gmail [dot] com
